DB_HOST     = "aws-1-ap-northeast-1.pooler.supabase.com"
DB_PORT     = 5432
DB_NAME     = "postgres"
DB_USER     = "postgres.cdjlfjmivsccssyaewde"
DB_PASSWORD = "c%#6fdY&5Crj*.r"

ANTHROPIC_API_KEY = "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"
